import MyGraph
#import MyGraph.testfunc as testfunc
MyGraph.testfunc()
g=MyGraph.Graph()
g.add_node(2,lhs=[],xlist=[], name="C-0")
g.add_node(3,lhs=[],xlist=[], name="D-1")
g.add_node(4, lhs=[],xlist=[], name="E-1")
g.add_node(5, lhs=[],xlist=[], name="F-1")
g.add_lhs(2, [1,"test","test"])
print(g.lhs(2))
g.add_mask(2, [2,3,4])
print(g.get_mask(2))
print(g.xlist(2))
g.add_xlist(2, [1, "t", "t"])
print(g.xlist(2))
g.add_mask(2,[1,2,3])
print(g.get_mask(2))
print(g.nodes)
print(g.nodes)
g.add_edge(2,3, myweight="1")
g.add_edge(2,6, myweight="1")
g.add_edge(4,5, myweight="2")
#g.remove_node(2)
g.set_atoms({"C":0, "D":1, "E":2,"F":3})
print(g.adj)
g.remove_node(3)
g.remove_node(6)
print(g.adj, g.nodes[4]["name"])
print(g.get_mol_adjs([g], [4]))
g.nodes[4]["name"]="Tr"
print(g.nodes[4])
c=g.copy()
print(c.adj, g.adj)
print(c.nodes, g.nodes)
print(c.lhs(2), g.lhs(2))
print(c.lhs(4), g.lhs(4), g.get_mask(2), c.get_mask(2))
print(c.get_mask(2), g.get_mask(2))
print(c.get_max, g.get_max)
print(g.lhs(2))
g.modify_lhs(2, 1, 5,"Test")
print(g.lhs(2))
g.add_xlist(4, [4, "Re", "P"])
print(g.xlist(4))
g.modify_xlist(4,4,7,"Pr")
print(g.xlist(4))
print(g.nodes, c.nodes)
print(g.adj, c.adj)
print(c.get_mol_adjs([c,c,g],[4,4,5]))